package com.date.backend.domain.safety.domain;

public enum SafetyCategory {
	EX_PARTNER_REPETITION,
	APPEARANCE_CRITICISM,
	AGE_OR_CONDITION_DISPARAGEMENT,
	MARRIAGE_OR_CHILDBIRTH_PRESSURE,
	SEXUAL_QUESTION,
	REPEATED_BOASTING,
	SARCASM_OR_DISRESPECT,
	AGGRESSIVE_ASSERTION,
	PERSONAL_INFORMATION_REQUEST,
	HATE_OR_DISCRIMINATION
}
