package com.date.backend.domain.growth.domain;
public enum TemperatureChangeReason {
    VERY_POSITIVE_EVALUATION, POSITIVE_EVALUATION, NEUTRAL_EVALUATION,
    NEGATIVE_EVALUATION, VERY_NEGATIVE_EVALUATION, NO_SHOW,
    EVALUATION_REVERSED, NO_SHOW_REVERSED
}
