CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
    `passwordResetTokenId` BIGINT NOT NULL AUTO_INCREMENT,
    `userId` BIGINT NOT NULL,
    `tokenHash` VARCHAR(64) NOT NULL,
    `expiresAt` DATETIME NOT NULL,
    `usedAt` DATETIME NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `PK_PASSWORD_RESET_TOKENS` PRIMARY KEY (`passwordResetTokenId`),
    CONSTRAINT `UK_PASSWORD_RESET_TOKENS_TOKEN_HASH` UNIQUE (`tokenHash`),
    CONSTRAINT `FK_USERS_TO_PASSWORD_RESET_TOKENS` FOREIGN KEY (`userId`)
        REFERENCES `users` (`userId`),
    INDEX `IDX_PASSWORD_RESET_TOKENS_USER_ID` (`userId`),
    INDEX `IDX_PASSWORD_RESET_TOKENS_EXPIRES_AT` (`expiresAt`)
);
