package com.date.backend.domain.notification.domain;

public enum NotificationType {
	MATCH_FOUND,
	MATCH_ACCEPTANCE_DEADLINE_SOON,
	MATCH_ACCEPTANCE_EXPIRED,
	MATCH_CONFIRMED,
	MATCH_REJECTED,
	MATCH_CANCELLED,
	SESSION_REMINDER_2H,
	SESSION_REMINDER_1H,
	SESSION_REMINDER_10M,
	MATCH_SETTING_RECOMMENDED
}
