import {
  type VisionConfig,
  visionConfigSchema,
} from "./VisionConfig.js";

export const defaultVisionConfig: VisionConfig = visionConfigSchema.parse({
  schemaVersion: 1,
  model: {
    wasmBasePath: "/mediapipe/wasm",
    modelAssetPath: "/models/face_landmarker.task",
    modelVersion: "mediapipe-face-landmarker-v1",
    ruleVersion: "vision-rule-v1",
    numFaces: 2,
    minFaceDetectionConfidence: 0.5,
    minFacePresenceConfidence: 0.5,
    minTrackingConfidence: 0.5,
    outputFaceBlendshapes: true,
    outputFacialTransformationMatrixes: true,
    preferredDelegate: "GPU",
  },
  frame: {
    analysisWidth: 480,
    analysisHeight: 360,
    maxInFlightFrames: 1,
    faceRoiPaddingRatio: 0.1,
    // These are starting points for normalized Laplacian variance, not product constants.
    blurVarianceFloor: 20,
    blurVarianceCeiling: 300,
  },
  worker: {
    initializationTimeoutMs: 15_000,
    maximumRestartAttempts: 1,
  },
  profiles: {
    HIGH: {
      targetFps: 5,
      enabledDetectors: [
        "FACE_QUALITY",
        "SCREEN_ATTENTION",
        "SMILE_EXPRESSION",
        "EXPRESSION_ACTIVITY",
        "NOD",
      ],
    },
    MEDIUM: {
      targetFps: 3,
      enabledDetectors: [
        "FACE_QUALITY",
        "SCREEN_ATTENTION",
        "SMILE_EXPRESSION",
        "EXPRESSION_ACTIVITY",
      ],
    },
    LOW: {
      targetFps: 1.5,
      enabledDetectors: ["FACE_QUALITY", "SCREEN_ATTENTION"],
    },
  },
  performanceGovernor: {
    overloadWindowMs: 10_000,
    recoveryWindowMs: 30_000,
    profileChangeCooldownMs: 15_000,
    maxProcessingBudgetRatio: 0.7,
    nodMinimumActualFps: 4.5,
  },
  calibration: {
    minimumUsableDurationMs: 3_000,
    targetUsableDurationMs: 5_000,
    maximumWallDurationMs: 10_000,
    minimumUsableFrames: 15,
    activityBaselineDurationMs: 20_000,
    trimRatio: 0.1,
    minimumInFrameRatio: 0.985,
    maximumAbsoluteYawDegrees: 25,
    maximumAbsolutePitchDegrees: 20,
    maximumAbsoluteRollDegrees: 20,
  },
  quality: {
    faceMissingEntryDurationMs: 600,
    faceMissingRecoveryDurationMs: 500,
    multipleFacesEntryDurationMs: 600,
    multipleFacesRecoveryDurationMs: 800,
    faceArea: {
      entry: 0.05,
      recovery: 0.075,
      entryDurationMs: 800,
      recoveryDurationMs: 800,
    },
    faceInFrame: {
      entry: 0.96,
      recovery: 0.985,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    brightness: {
      entry: 0.25,
      recovery: 0.33,
      entryDurationMs: 1_000,
      recoveryDurationMs: 1_000,
    },
    blur: {
      entry: 0.3,
      recovery: 0.42,
      entryDurationMs: 1_000,
      recoveryDurationMs: 1_000,
    },
    extremeYaw: {
      entryDegrees: 35,
      recoveryDegrees: 28,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    extremePitch: {
      entryDegrees: 25,
      recoveryDegrees: 20,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    extremeRoll: {
      entryDegrees: 30,
      recoveryDegrees: 24,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    analysisRecoveryWarmupMs: 1_000,
    defaultEventConfidence: 0.85,
  },
  screenAttention: {
    yawEntryDegrees: 20,
    yawRecoveryDegrees: 12,
    pitchEntryDegrees: 15,
    pitchRecoveryDegrees: 10,
    centerXEntryDelta: 0.18,
    centerXRecoveryDelta: 0.1,
    centerYEntryDelta: 0.15,
    centerYRecoveryDelta: 0.08,
    awayMinimumDurationMs: 1_500,
    recoveryMinimumDurationMs: 500,
    prolongedDurationMs: 5_000,
    cooldownMs: 2_000,
    emaAlpha: 0.35,
    defaultEventConfidence: 0.82,
  },
  smile: {
    smileWeight: 0.8,
    cheekWeight: 0.2,
    entryAbsoluteScore: 0.35,
    entryBaselineDelta: 0.18,
    recoveryBaselineDelta: 0.1,
    minimumDurationMs: 400,
    recoveryDurationMs: 300,
    mergeGapMs: 700,
    emaAlpha: 0.4,
    defaultEventConfidence: 0.8,
  },
  expressionActivity: {
    windowMs: 8_000,
    warmupMs: 5_000,
    lowMinimumDurationMs: 8_000,
    recoveryMinimumDurationMs: 2_000,
    fallbackLowThreshold: 0.08,
    baselineLowRatio: 0.6,
    emaAlpha: 0.25,
  },
  nod: {
    enabledByDefault: false,
    minimumAmplitudeDegrees: 7,
    maximumAmplitudeDegrees: 15,
    returnToleranceDegrees: 4,
    minimumDurationMs: 300,
    maximumDurationMs: 1_200,
    cooldownMs: 800,
  },
  events: {
    metricSnapshotIntervalMs: 1_000,
  },
  transport: {
    batchIntervalMs: 500,
    maxBufferedEvents: 100,
    maxBufferedAgeMs: 30_000,
  },
});
