import {
  type VisionConfig,
  visionConfigSchema,
} from "./VisionConfig.js";

export const defaultVisionConfig: VisionConfig = visionConfigSchema.parse({
  schemaVersion: 2,
  model: {
    wasmBasePath: "/mediapipe/wasm",
    modelAssetPath: "/models/face_landmarker.task",
    modelVersion: "mediapipe-face-landmarker-v1",
    ruleVersion: "vision-rule-v2",
    numFaces: 2,
    minFaceDetectionConfidence: 0.5,
    minFacePresenceConfidence: 0.5,
    minTrackingConfidence: 0.5,
    outputFaceBlendshapes: true,
    outputFacialTransformationMatrixes: true,
    preferredDelegate: "GPU",
  },
  frame: {
    analysisWidth: 480,
    analysisHeight: 360,
    maxInFlightFrames: 1,
    faceRoiPaddingRatio: 0.1,
    // These are starting points for normalized Laplacian variance, not product constants.
    blurVarianceFloor: 20,
    blurVarianceCeiling: 300,
  },
  worker: {
    initializationTimeoutMs: 15_000,
    maximumRestartAttempts: 1,
  },
  profiles: {
    HIGH: {
      targetFps: 5,
      enabledDetectors: [
        "FACE_QUALITY",
        "SCREEN_ATTENTION",
        "SMILE_EXPRESSION",
        "EXPRESSION_ACTIVITY",
        "NOD",
      ],
    },
    MEDIUM: {
      targetFps: 3,
      enabledDetectors: [
        "FACE_QUALITY",
        "SCREEN_ATTENTION",
        "SMILE_EXPRESSION",
        "EXPRESSION_ACTIVITY",
      ],
    },
    LOW: {
      targetFps: 1.5,
      enabledDetectors: ["FACE_QUALITY", "SCREEN_ATTENTION"],
    },
  },
  performanceGovernor: {
    overloadWindowMs: 10_000,
    recoveryWindowMs: 30_000,
    profileChangeCooldownMs: 15_000,
    maxProcessingBudgetRatio: 0.7,
    nodMinimumActualFps: 4.5,
  },
  behaviorPolicy: {
    suspensionGraceMs: 1_000,
    recoveryWarmupMs: 500,
  },
  calibration: {
    setupRecommendedDurationMs: 15_000,
    stabilizationDurationMs: 1_000,
    stabilizationMinimumFrames: 3,
    recoveryWarmupMs: 1_000,
    minimumUsableDurationMs: 3_000,
    targetUsableDurationMs: 5_000,
    maximumWallDurationMs: 12_000,
    minimumUsableFrames: 15,
    partialMinimumUsableFrames: 8,
    readyMinimumConfidence: 0.75,
    partialMinimumConfidence: 0.55,
    priorShrinkageSampleCount: 60,
    targetFps: 5,
    minimumPreferredFps: 3,
    activityBaselineDurationMs: 20_000,
    trimRatio: 0.1,
    minimumInFrameRatio: 0.985,
    maximumAbsoluteYawDegrees: 25,
    maximumAbsolutePitchDegrees: 20,
    maximumAbsoluteRollDegrees: 20,
  },
  adaptiveBaseline: {
    windowMs: 15_000,
    startEligibleRatio: 0.85,
    maintainEligibleRatio: 0.7,
    minimumObservableMs: 10_000,
    longGapMs: 2_000,
    recoveryWarmupMs: 2_000,
    poseHalfLifeMs: 90_000,
    geometryHalfLifeMs: 120_000,
    gazeHalfLifeMs: 240_000,
    maximumPoseDriftDegrees: 8,
    maximumCenterDrift: 0.08,
    maximumAreaDrift: 0.1,
    maximumGazeDrift: 0.05,
    reanchorMinimumStableMs: 30_000,
    reanchorMinimumSamples: 60,
  },
  quality: {
    faceMissingEntryDurationMs: 600,
    faceMissingRecoveryDurationMs: 500,
    multipleFacesEntryDurationMs: 600,
    multipleFacesRecoveryDurationMs: 800,
    faceArea: {
      entry: 0.025,
      recovery: 0.05,
      entryDurationMs: 800,
      recoveryDurationMs: 800,
    },
    faceAreaMaximum: {
      entry: 0.55,
      recovery: 0.45,
      entryDurationMs: 600,
      recoveryDurationMs: 800,
    },
    faceInFrame: {
      entry: 0.96,
      recovery: 0.985,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    brightness: {
      entry: 0.25,
      recovery: 0.33,
      entryDurationMs: 1_000,
      recoveryDurationMs: 1_000,
    },
    // A low value means the face ROI is much darker than its background.
    backlight: {
      entry: 0.35,
      recovery: 0.5,
      entryDurationMs: 600,
      recoveryDurationMs: 800,
    },
    blur: {
      entry: 0.3,
      recovery: 0.42,
      entryDurationMs: 1_000,
      recoveryDurationMs: 1_000,
    },
    extremeYaw: {
      entryDegrees: 35,
      recoveryDegrees: 28,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    extremePitch: {
      entryDegrees: 25,
      recoveryDegrees: 20,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    extremeRoll: {
      entryDegrees: 30,
      recoveryDegrees: 24,
      entryDurationMs: 500,
      recoveryDurationMs: 500,
    },
    analysisRecoveryWarmupMs: 1_000,
  },
  screenAttention: {
    yawEntryDegrees: 20,
    yawRecoveryDegrees: 12,
    pitchEntryDegrees: 15,
    pitchRecoveryDegrees: 10,
    centerXEntryDelta: 0.18,
    centerXRecoveryDelta: 0.1,
    centerYEntryDelta: 0.15,
    centerYRecoveryDelta: 0.08,
    // Iris ratios are eye-local proxies, not a claim about the exact viewed object.
    gazeHorizontalEntryDelta: 0.18,
    gazeHorizontalRecoveryDelta: 0.1,
    gazeVerticalEntryDelta: 0.2,
    gazeVerticalRecoveryDelta: 0.12,
    blinkEntryScore: 0.55,
    blinkRecoveryScore: 0.35,
    blinkRecoveryWarmupMs: 250,
    minimumBinocularAgreementScore: 0.65,
    binocularHorizontalTolerance: 0.12,
    binocularVerticalTolerance: 0.15,
    headWeight: 0.45,
    faceCenterWeight: 0.15,
    irisWeight: 0.4,
    headOnlyWeight: 0.75,
    centerOnlyWeight: 0.25,
    attentionAwayScore: 40,
    attentionRecoveryScore: 65,
    minimumEventConfidence: 0.65,
    minimumRecoveryConfidence: 0.6,
    minimumAwayObservations: 4,
    minimumRecoveryObservations: 2,
    irisOnlyScore: 20,
    irisOnlyMinimumReliability: 0.8,
    irisOnlyMinimumConfidence: 0.75,
    irisOnlyMinimumDurationMs: 2_000,
    irisOnlyMinimumObservations: 5,
    suspendedConfidenceThreshold: 0.45,
    fallbackYawDegrees: 40,
    fallbackPitchDegrees: 30,
    fallbackMinimumDurationMs: 2_000,
    fallbackMinimumMeasurementConfidence: 0.7,
    awayMinimumDurationMs: 1_500,
    recoveryMinimumDurationMs: 500,
    prolongedDurationMs: 5_000,
    cooldownMs: 2_000,
    emaAlpha: 0.35,
  },
  smile: {
    // A naturally raised mouth-corner baseline should not trigger "please smile".
    baselinePromptSuppressionScore: 0.15,
    subtleAbsoluteScore: 0.2,
    smileAbsoluteScore: 0.4,
    strongAbsoluteScore: 0.7,
    subtleDelta: 0.08,
    smileDelta: 0.18,
    strongDelta: 0.3,
    subtleRecoveryAbsoluteScore: 0.15,
    smileRecoveryAbsoluteScore: 0.32,
    strongRecoveryAbsoluteScore: 0.58,
    subtleRecoveryDelta: 0.04,
    smileRecoveryDelta: 0.1,
    strongRecoveryDelta: 0.18,
    smileMinimumDurationMs: 400,
    smileRecoveryDurationMs: 300,
    smileMergeGapMs: 700,
    smileMinimumObservations: 3,
    strongMinimumDurationMs: 300,
    strongMinimumObservations: 2,
    maximumFrameGapMs: 500,
    maintainedDurationMs: 3_000,
    minimumMeasurementConfidence: 0.75,
    asymmetryConfidenceStart: 0.15,
    asymmetryHigh: 0.3,
    asymmetryHold: 0.45,
    fallbackMaximumAsymmetry: 0.25,
    fallbackMinimumSideScore: 0.65,
    fallbackMinimumDurationMs: 500,
    fallbackMinimumObservations: 3,
    fallbackMinimumMeasurementConfidence: 0.7,
    emaHalfLifeMs: 300,
  },
  expressionActivity: {
    upperFaceBlendshapeNames: [
      "browInnerUp",
      "browDownLeft",
      "browDownRight",
      "eyeSquintLeft",
      "eyeSquintRight",
    ],
    lowerFaceBlendshapeNames: [
      "mouthSmileLeft",
      "mouthSmileRight",
      "mouthFrownLeft",
      "mouthFrownRight",
      "mouthPressLeft",
      "mouthPressRight",
    ],
    blendshapeWeight: 0.7,
    landmarkWeight: 0.3,
    maximumFrameGapMs: 500,
    rateNormalizationPerSecond: 2,
    emitBehaviorEvents: false,
    windowMs: 8_000,
    warmupMs: 5_000,
    minimumWindowSamples: 10,
    lowMinimumDurationMs: 8_000,
    recoveryMinimumDurationMs: 2_000,
    fallbackLowThreshold: 0.08,
    fallbackRecoveryThreshold: 0.12,
    baselineLowRatio: 0.6,
    baselineRecoveryRatio: 0.85,
    emaAlpha: 0.25,
  },
  nod: {
    enabledByDefault: false,
    // MediaPipe pitch sign is isolated in configuration for device-video validation.
    downwardPitchSign: 1,
    minimumAmplitudeDegrees: 7,
    maximumAmplitudeDegrees: 15,
    returnToleranceDegrees: 4,
    minimumReversalDegrees: 2,
    minimumDownstrokeMs: 120,
    minimumUpstrokeMs: 120,
    maximumDownHoldMs: 500,
    minimumDurationMs: 300,
    maximumDurationMs: 1_200,
    cooldownMs: 800,
    emaAlpha: 0.5,
    defaultEventConfidence: 0.75,
  },
  events: {
    metricSnapshotIntervalMs: 1_000,
  },
  transport: {
    batchIntervalMs: 500,
    maxBufferedEvents: 100,
    maxBufferedAgeMs: 30_000,
  },
});
